apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::713921967372:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-YJ7ZPSC87BC5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::713921967372:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-17T12:00:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1742"
  uid: 613c861a-b12b-4d70-844d-ec4553139fc5
